"use client";
import { StoreContext } from "@/context/store";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreContext>
          <div className="bg-gray-100">
            <div className="container mx-auto px-4">{children}</div>
          </div>
        </StoreContext>
      </body>
    </html>
  );
}
